### ISSUE TITLE
太low了

### ISSUE THREAD

**Issue by starzou** [ShuyunFF2E/ccms-components#1]
angular.js用es6写，代码真是恶心到爆
排版格式太low，差评

**Comment by kuitos** [comment]
呵呵

**Comment by starzou** [comment]
能不能用webcomponents 实现一套组件库，跨框架

**Comment by kuitos** [comment]
且不说现在践行webcomponents需要polymer或者polyfill而它们与框架无异的事实了，现代的 组件框架/库 要向上兼容webcomponents都没什么难度而且有一系列工程化手段做辅助，生态上更是webcomponent不能比的。我理解的面向未来指代的是应用的演化能力，具体就是 下层的 业务/数据 模型 可以脱离框架运作，而视图层只需要兼容webcomponents规范即可。
在现在这个时间点看，webcomponents只存在理论上的优势
