### ISSUE TITLE
package.json 的两个问题

### ISSUE THREAD

**Issue by hjzheng** [ShuyunFF2E/ccms-components#328]
![image](https://cloud.githubusercontent.com/assets/4166657/22816443/0ef1ba0c-ef9d-11e6-9317-ee85e4eff255.png)

1. json-loader 应放到 devDependencies
2.angular-es-utils 目前已经 2.1.2，依赖的这个版本有些低，看要不要升级

**Comment by arzyu** [comment]
@hjzheng `json-loader` 调整到了 `devDependencies`， #329 。升级 `angular-es-utils` v2.1.2 会导致 `npm run test` 报错。

**Comment by hjzheng** [comment]
@arzyu 主要是 PhantomJS 不支持 proxy 对象，这个可以修改 karma 配置改成 chrome 或 firefox
