### ISSUE TITLE
cc-dropdown选择searchable='true'时，model无法选中默认值。

### ISSUE THREAD

**Issue by peachlemon** [ShuyunFF2E/ccms-components#397]

**Comment by peachlemon** [comment]
<cc-dropdown-select model="value" datalist="list" searchable="true" ></cc-dropdown-select>
     
$scope.datalist = [
{value: 'name', title: '名称'}
]；
$scope.value = 'name';

**Comment by hjzheng** [comment]
已修复,见:https://github.com/ShuyunFF2E/ccms-components/pull/398
