### ISSUE TITLE
Firefox 中 cc-icon tooltip 偶尔会出现不能消失或闪烁不能显示的情况

### ISSUE THREAD

**Issue by arzyu** [ShuyunFF2E/ccms-components#404]
```html
<cc-icon symbol="icon-question-mark" cc-tooltip="'拖拽热点到图片中'"></cc-icon>
```
![qq20171127-145052](https://user-images.githubusercontent.com/1270145/33254160-677cfe88-d382-11e7-8cf9-9761700fea03.png)

**Comment by hjzheng** [comment]
I will fix it.

**Comment by hjzheng** [comment]
refer to pull request #405
