### ISSUE TITLE
运用到cc-bind-html，可能被XSS攻击。

### ISSUE THREAD

**Issue by peachlemon** [ShuyunFF2E/ccms-components#432]
![image](https://user-images.githubusercontent.com/8087092/42750715-c93a297c-891a-11e8-8093-7ede49570b9b.png)
这样的代码，如果数据源动态，可能存在XSS攻击风险。

**Comment by peachlemon** [comment]
@hjzheng 豪举， 你关注下。

**Comment by hjzheng** [comment]
好的

**Comment by kuitos** [comment]
可以考虑 ngBindHtml 替换一下

**Comment by hjzheng** [comment]
#433 用ngBindHtml替换一下
